type: custom:clock-weather-card
entity: weather.tfam_home
title: Home
sun_entity: sun.sun
temperature_sensor: sensor.outdoor_temp
humidity_sensor: sensor.outdoor_humidity
weather_icon_type: line
animated_icon: true
forecast_rows: 5
locale: en-GB
time_pattern: h:mm a
time_format: 12
date_pattern: ccc, d.MM.yy
hide_today_section: false
hide_forecast_section: false
show_humidity: true
hide_clock: true
hide_date: true
hourly_forecast: false
use_browser_time: false
time_zone: null
show_decimal: false
apparent_sensor: sensor.real_feel_temperature
aqi_sensor: sensor.air_quality_index
card_mod:
  style: |
    ha-card {
      margin: 16px;  # Adds external spacing
      padding: 16px;  # Adds internal spacing
      box-shadow: inset 0px 0px 10px rgba(255, 255, 255, 0.2), 0px 0px 20px 5px rgba(77, 163, 255, 0.6);  # Shadow for depth
    }
